### ISSUE TITLE
Unicode NameError

### ISSUE THREAD

**Issue by AngelBerihuete** [artur-shaik/mutt2task#3]
Dear artur-shaik I'm trying to use your mutt2task file, but I get this error:

`
Traceback (most recent call last):
  File "/home/angel/.local/bin/mutt2task.py", line 59, in <module>
    body += unicode(
NameError: name 'unicode' is not defined
`
Any help will be welcome.

**Comment by artur-shaik** [comment]
Look like I need to upgrade script to support python3. For now, you can (if you can) use python 2 to run script.

**Comment by AngelBerihuete** [comment]
Yes, I've created an environment with Conda and it works perfectly. It'd be good to upgrade the script to support python 3.
Many thanks!
